### ISSUE TITLE
Repeater multilanguage in conflict with static page (url field)

### ISSUE THREAD

**Issue by mberizzo** [rainlab/translate-plugin#183]
Steps:
1. Add new language (total: 2)
2. Create "Skills" layout (skills.htm) with static page component
3. Put repeater code into previous layout:
`	{repeater tab="Skills" name="skills" prompt="add skill"}
	    {text name="skill_name" label="Name"}{/text}
	{/repeater}`
4. Go to "Pages"
5. Create new page and set "Skills" layout
6. Click on "Skills" tab
7. Click "add skill"

Expected:
See one text field with name "viewBag[skills][1][skill_name]"

Current:
There are two text fields with names: "viewBag[skills][1][skill_name]" (correct) and "viewBag[skills][1][viewBag][url]" (error) and if you try complete this field with "some text", you can see an url error alert.

**Comment by daftspunk** [comment]
Please confirm this was not already fixed by #54.

**Comment by mberizzo** [comment]
It is not solved yet.

steps:
* composer update
* force update (backend)

**Comment by daftspunk** [comment]
You may need to [enable bleeding edge updates](http://octobercms.com/docs/setup/configuration#edge-updates), or wait for these changes to become stable.

**Comment by mberizzo** [comment]
Good, now i have "'edgeUpdates' => true" and run "php artisan october:update".

But there is another problem: when i switch languages, in a repeater tab, it shows this message "Call to undefined method October\Rain\Halcyon\Builder::forceFill()" on line 776 of /home/vagrant/Code/October/vendor/october/rain/src/Halcyon/Builder.php"

**Comment by daftspunk** [comment]
It is probably because the composer version being sent is the stable version, where you need the `develop` version. There is a way to get composer to ask for bleeding edge updates (`develop`), I just can't seem to find it at the moment.

**Comment by mberizzo** [comment]
Still not working! (php artisan october:update - with 'edgeUpdates' => true -)

And there is another problem:
![october_error](https://cloud.githubusercontent.com/assets/2679457/20248946/283f0312-a9ce-11e6-9bf8-3428330abf1e.png)

**Comment by mberizzo** [comment]
hi! what about this?
