### ISSUE TITLE
Secondary languages translations overrides primary translations of Settings-Model fields

### ISSUE THREAD

**Issue by jannikholsten** [rainlab/translate-plugin#711]
Hi, 
I'm struggeling with translation in Settings-Model. I've got three different languages for my page, german, english and spanish. German is my default language, which means, it's my primary site. The issue now is, everytime I edit the translation for english or spanish, it overrides the german translation to the language I just edited. Is that probably a bug in the translate-plugin or did I miss some important code in my settings model? 
Thanks for any help.

`public $implement = [\System\Behaviors\SettingsModel::class, \RainLab\Translate\Behaviors\TranslatableModel::class];`
`public $translatable = ['linktext', 'map_hint_text', 'map_hint_btn_text', 'map_hint_cookie_text'];`

**Comment by daftspunk** [comment]
This is definitely a bug coming from the core. It has been fixed in the next patch release of October CMS (v3.2.8). It should be released early next week.

Thanks

**Comment by idOn-studio** [comment]
I still have this problem, latest version of october and latest version of the plugin installed directly from the marketplace. In addition, the drop-down to select the language next to the field is not displayed at all

<img width="1471" alt="Screenshot 2023-03-20 alle 14 59 30" src="https://user-images.githubusercontent.com/128391721/226362729-83861165-ac78-40b5-a09c-afae41beccf7.png">

**Comment by jannikholsten** [comment]
For me, everything works as expected now since the latest updates

> In addition, the drop-down to select the language next to the field is not displayed at all

There won't be a dropdown next to the field. You have to switch the language on the top right corner where you also switch the current site.
![Schnappschuss_032023_034945_PM](https://user-images.githubusercontent.com/66406579/226377072-9b0f6281-da64-4913-9807-1efd0e768475.jpg)

**Comment by idOn-studio** [comment]
I just discovered that to work properly within the blueprint you need to include the "multisite" option. This way it works correctly
